name: Prettier
on: [push]

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prettier
        uses: jgierer12/prettier-action@v2.0.0
        with:
          args: --write .